# Generated by Django 2.2.16 on 2022-04-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220416_1049'),
        ('reviews', '0005_auto_20220415_0023'),
    ]

    operations = [
    ]
