# Generated by Django 2.2.16 on 2022-04-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_user_confirmation_code'),
        ('reviews', '0009_auto_20220419_0020'),
    ]

    operations = [
    ]
