# Generated by Django 2.2.16 on 2022-04-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220422_1949'),
        ('reviews', '0010_merge_20220420_2235'),
    ]

    operations = [
    ]
